[ADD] QueryBulider 기능 추가
wecode-bootcamp-korea/48-2nd-FIVEGUYS-backend pull request #11
Opened 2023-08-30 12:17 UTC by SIKR2

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [ O ] 기능 추가
- [ ] 데이터베이스 작업
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 - 해당 브랜치(PR)에서 구현하고자 하는 하나의 목표 작성
- JUMPIT '직무탐색' 페이지 조회순 및 최신순 필터링 및 쿼리빌더.

<br />

## :: 구현 사항 설명 - 해당 브랜치(PR)에서 작업한 내용 작성
- JUMPIT '직무탐색' 페이지에서 쿼리스트링으로 요청 들어오는 부분 관련 처리 기능 추가하였습니다.
- JUMPIT '직무탐색' 페이지에서 ?sort=popular(조회순,인기순) 및 ?sort=reg_dt(최신순) 으로 필터링 및 리스팅 되는 기능 추가하였습니다.

<br />

## :: 테스트 결과 이미지
1. Server가 잘 동작하는지 확인할 수 있는 Terminal 캡쳐 이미지
2. 
<img width="389" alt="스크린샷 2023-08-30 오후 9 13 45" src="https://github.com/wecode-bootcamp-korea/48-2nd-FIVEGUYS-backend/assets/121228839/dd777c83-bb6f-4a1b-bbf9-68abb53ee9e8">

3. Postman(Client Tool)을 이용한 API 테스트 결과 이미지
4. 
<img width="761" alt="스크린샷 2023-08-30 오후 9 15 13" src="https://github.com/wecode-bootcamp-korea/48-2nd-FIVEGUYS-backend/assets/121228839/bd2e4251-c328-4c61-901b-7e6d22027bb8">
<img width="792" alt="스크린샷 2023-08-30 오후 9 15 47" src="https://github.com/wecode-bootcamp-korea/48-2nd-FIVEGUYS-backend/assets/121228839/8f66c27e-3ae8-4530-a4a1-696edd5d43b1">
<img width="808" alt="스크린샷 2023-08-30 오후 9 16 29" src="https://github.com/wecode-bootcamp-korea/48-2nd-FIVEGUYS-backend/assets/121228839/87e4f016-0ed9-435c-9710-3a4e171e05a1">
<img width="794" alt="스크린샷 2023-08-30 오후 9 17 03" src="https://github.com/wecode-bootcamp-korea/48-2nd-FIVEGUYS-backend/assets/121228839/43f46bf9-e22c-4102-91fa-50d333e3a9c6">

5. 작성한 Test Code가 잘 통과했는지 확인할 수 있는 이미지
6. DB 작업 PR인 경우 Table 생성 및 수정 결과에 대해 확인할 수 있는 이미지

<br />

## :: 기타 질문 및 특이 사항
- 바쁘시겠지만 확인 부탁드리겠습니다. 감사합니다!

2023-08-30 13:12 UTC, kyeongraekim requested changes

2023-08-30 13:12 UTC, kyeongraekim commented on db/migrations/20230829120700_modify_job_postings1.sql
> +
- 현재 mock data 값을 넣는 sql 문을 github 상의 공간에 함께 올려주셨는데, 실무 단계에서 해당 목데이터의 기입은 migration 폴더단위로 관리하지 않습니다.
- 해당 내용을 온전하게 잘 기입한 데이터셋이 잘 구축 되었다면 마이그레이션 파일 내에서 삭제하여주세요!

2023-08-31 03:25 UTC, SIKR2 commented on db/migrations/20230829120700_modify_job_postings1.sql
> +
삭제하고 다시 add / commit / push 드렸습니다. 확인 부탁드리겠습니다. 감사합니다.!

2023-08-31 03:27 UTC, kyeongraekim approved these changes
LGTM!~

2023-08-31 03:27 UTC, merged