Add: initial environment set-up
wecode-bootcamp-korea/48-2nd-FIVEGUYS-backend pull request #3
Opened 2023-08-22 10:13 UTC by Jinhan-Han-Jeremy

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [ ] 기능 추가
- [ ] 데이터베이스 작업
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 - 해당 브랜치(PR)에서 구현하고자 하는 하나의 목표 작성
- email, password를 이용한 로그인 기능 구현 (예시)

<br />

## :: 구현 사항 설명 - 해당 브랜치(PR)에서 작업한 내용 작성
- API 호출 시 필요한 값들에 대한 유효성 검사 (예시)

<br />

## :: 테스트 결과 이미지
1. Server가 잘 동작하는지 확인할 수 있는 Terminal 캡쳐 이미지
2. Postman(Client Tool)을 이용한 API 테스트 결과 이미지
3. 작성한 Test Code가 잘 통과했는지 확인할 수 있는 이미지
4. DB 작업 PR인 경우 Table 생성 및 수정 결과에 대해 확인할 수 있는 이미지

<br />

## :: 기타 질문 및 특이 사항
- 제가 작성한 함수의 로직이 너무 복잡하다고 생각이 됩니다. 더 효율적인 방법이 없을까요? (예시)

2023-08-22 11:08 UTC, kyeongraekim requested changes
다음의 마이너한 내역 수정 부탁드립니다!~

2023-08-22 11:08 UTC, kyeongraekim commented on api/models/dataSource.js
> +  type: 'mysql',
- 해당 내용은 .env 의 DB_TYPE의 환경변수 내용을 이용하여 데이터베이스 서버와의 연동을 완성시켜주세요!

2023-08-22 11:08 UTC, kyeongraekim commented on db/20230822051804_alter_tablename.sql
> +-- migrate:up
- 현재 디렉토리 구조 위치가 올바르지 않아 보입니다. 재 확인 부탁드립니다.

2023-08-22 11:08 UTC, kyeongraekim commented on db/migrations/20230822041101_users.sql
> +
- 비어있는 파일로 보여지네요!

2023-08-22 11:08 UTC, kyeongraekim commented on db/migrations/20230822041918_users.sql
> +  birthday char(8),
- birthday 는 date 필드로 관리하여 생년월일 기준의 나이 계산 등에 유리하게 설정하여주세요.

2023-08-23 03:12 UTC, closed without merging

2023-08-23 03:13 UTC, Jinhan-Han-Jeremy commented
폴더 기본구성 만들었습니다.