[Add] signup-signin
wecode-bootcamp-korea/48-2nd-FIVEGUYS-backend pull request #4
Opened 2023-08-23 10:03 UTC by kmjmarine

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [o] 기능 추가
- [ ] 데이터베이스 작업
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 - 해당 브랜치(PR)에서 구현하고자 하는 하나의 목표 작성
- 회원가입, 로그인 기능 구현

<br />

## :: 구현 사항 설명 - 해당 브랜치(PR)에서 작업한 내용 작성
- 이메일 입력 후 해당 이메일이 없다면 회원가입으로 있다면 로그인 화면으로 분기처리함

<br />

## :: 테스트 결과 이미지
<img width="274" alt="스크린샷 2023-08-23 오후 6 58 29" src="https://github.com/wecode-bootcamp-korea/48-2nd-FIVEGUYS-backend/assets/87652668/e56a5b6b-eeb8-462a-ace7-1e76d8bd7916">
<img width="276" alt="스크린샷 2023-08-23 오후 6 59 19" src="https://github.com/wecode-bootcamp-korea/48-2nd-FIVEGUYS-backend/assets/87652668/cc004543-42f0-4ee9-b7e4-a4ba86fa868c">
<img width="1379" alt="스크린샷 2023-08-23 오후 7 01 01" src="https://github.com/wecode-bootcamp-korea/48-2nd-FIVEGUYS-backend/assets/87652668/547bccec-87a0-45b1-85c2-402794b57446">

<br />

## :: 기타 질문 및 특이 사항
- 회원가입 시 이메일 인증 절차는 선택과제로 진행할 예정입니다.

2023-08-23 11:04 UTC, kyeongraekim requested changes
게시글에 대한 코드는 회원 인증/인가 코드와 상관이 없어 보입니다. 해당 브랜치를 분리하여 푸시하는 전략을 선택해주세요!~

2023-08-23 15:56 UTC, kmjmarine commented
게시글에 대한 코드는 커밋에서 삭제했습니다.

2023-08-24 06:47 UTC, kyeongraekim requested changes
게시글에 대한 분리 작업을 잘해주셨네요! 다만 현재 PR 상 필히 존재해야하는 root 디렉토리내 모든 파일까지 현재 삭제가 되어서 해당 내용을 복원하여 다시 푸시해주시면 되겠습니다!

해당 내용이 머지가 되면 깃헙 원격 레포지토리상 app.js, package.json 등이 내역을 삭제하는 현상을 초래할 예정이오니 이점 참고 바랍니다!

2023-08-24 08:23 UTC, kmjmarine commented
삭제현상이 초래될 
app.js, 
package.json, 
/models/dataSource.js, 
/utils/error.js, 
pull_request_template.md ADD하여 재 커밋 했습니다.
확인 부탁 드립니다.

2023-08-24 08:36 UTC, kyeongraekim approved these changes
LGTM!~

2023-08-24 08:36 UTC, merged