[MODIFY] resumeList
wecode-bootcamp-korea/48-2nd-FIVEGUYS-backend pull request #6
Opened 2023-08-25 11:31 UTC by kmjmarine

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [ ] 기능 추가
- [ ] 데이터베이스 작업
- [ ] 리팩토링
- [ ] 버그 수정
- [O] 컨벤션 수정

<br />

## :: 구현 목표 - 해당 브랜치(PR)에서 구현하고자 하는 하나의 목표 작성
- 브렌치 명 변경 
- as-is : resumeList 
- to-be : feature/resumeList
- FE에서 전달되는 값의 하드코딩된 부분 삭제

<br />

## :: 구현 사항 설명 - 해당 브랜치(PR)에서 작업한 내용 작성
- api/controllers/resumeController.js 하드 코드 부분 수정
- postman에서 테스트 후 정상 작동 확인 완료

<br />

## :: 테스트 결과 이미지
1. Server가 잘 동작하는지 확인할 수 있는 Terminal 캡쳐 이미지
<img width="269" alt="스크린샷 2023-08-25 오후 8 30 58" src="https://github.com/wecode-bootcamp-korea/48-2nd-FIVEGUYS-backend/assets/87652668/8f487151-70e2-4b6e-bb82-65206d06da51">
2. Postman(Client Tool)을 이용한 API 테스트 결과 이미지
<img width="286" alt="스크린샷 2023-08-25 오후 8 27 52" src="https://github.com/wecode-bootcamp-korea/48-2nd-FIVEGUYS-backend/assets/87652668/01d27ae2-ec43-43a9-868f-5b4b8d57f0b9">
3. 작성한 Test Code가 잘 통과했는지 확인할 수 있는 이미지
<img width="649" alt="스크린샷 2023-08-25 오후 8 30 00" src="https://github.com/wecode-bootcamp-korea/48-2nd-FIVEGUYS-backend/assets/87652668/9b124ccf-3ca9-4a55-93a9-6445491c0e12">

<br />

## :: 기타 질문 및 특이 사항
- 브렌치명이 컨벤션에 맞지 않아 수정했는데 기존 PR이 없어져서 재작성 드립니다.

2023-08-28 08:02 UTC, kyeongraekim requested changes

2023-08-28 08:02 UTC, kyeongraekim commented on api/controllers/resumeController.js
> +  }
- 해당 내용은, 다음의 방향으로 표현해볼 수 있겠네요!
- 함수 생성기를 만들어서 불필요한 if 문의 무한 증식을 조금은 피하는 방법입니다!

``` javascript
  const createSectionIfDataExists = async (data, createFunction) => {
    if (resumeId && data) {
      await createFunction(resumeId, data);
    }
  };

  await createSectionIfDataExists(educations, resumeService.createEducation);
  await createSectionIfDataExists(careers, resumeService.createCareer);
  await createSectionIfDataExists(projects, resumeService.createProject);
  await createSectionIfDataExists(addfiles, resumeService.createAddFile);

2023-08-28 08:02 UTC, kyeongraekim commented on api/models/resumeDao.js
> +      SELECT r.id AS resumeId, u.email, u.birthday, u.phone_number, r.title, r.display, r.github_url, r.notion_url, r.blog_url,
- 가독성 확보를 위해 해당 SELECT 문의 라인별 브레이킹을 주시면 좋을 것 같습니다~

2023-08-28 08:02 UTC, kyeongraekim commented on api/models/resumeDao.js
> +  });
- 해당 내용은 for 문 이후에 배열을 자연스래 만들어주는 map 함수를 써볼 수 있는 기획 처럼 보여지네요!

```
const educationsQuery = educations.map((item) => {
  return `(
    '${resumeId}',
    '${item.graduatedYear}',
    '${item.graduatedMonth}',
    '${item.schoolType}',
    '${item.schoolName}'
  )`;
});

2023-08-28 08:13 UTC, kyeongraekim requested changes

2023-08-28 08:13 UTC, kyeongraekim commented on api/models/resumeDao.js
> +      `
- 해당 내용은 ? place holder 및 builk insert 개념을 그대로 이용하여 동일하게 아래와 같이 표현할 수 있습니다.
- SQL Injection을 막아낼 수 있는 최소한의 장치를 이용한 방법임으로 아래와 같이 수정을 권장드립니다~

``` javascript
const createCareer = async (resuemeId, careers) => {
  const careersQueryValues = careers.map(item => [
    resuemeId,
    item.startYear,
    item.startMonth,
    item.endYear,
    item.endMonth,
    item.companyName,
    item.division,
    item.role,
    item.developer
  ]);

  try {
    const createCareers = await dataSource.query(
      `
        INSERT INTO resume_career (resume_id, start_year, start_month, end_year, end_month, company_name, division, role, developer) 
        VALUES 
        ?
      `,
      [careersQueryValues]
    );
    console.log(`${createCareers.affectedRows} careers inserted.`);
  } catch (error) {
    console.error('Error inserting careers:', error);
  }
};

2023-08-28 12:22 UTC, kmjmarine commented
가이드 주신 내용으로 수정 적용 했습니다.
검토 부탁 드립니다.

2023-08-29 03:14 UTC, kyeongraekim approved these changes
LGTM!~

2023-08-29 03:14 UTC, merged