[MODIFY ] Feature/signup signin token 값 추가
wecode-bootcamp-korea/48-2nd-FIVEGUYS-backend pull request #7
Opened 2023-08-25 11:56 UTC by kmjmarine

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [o] 기능 추가
- [ ] 데이터베이스 작업
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 - 해당 브랜치(PR)에서 구현하고자 하는 하나의 목표 작성
- token 값 수정 
- as-is : id: user.id
- to-be : id: user.id, email: user.email, username: user.username
- 로그인 완료 후 accessToken 반환 시 username: payload.user_name, email: payload.email를 추가로 FE에 response 함

<br />

## :: 구현 사항 설명 - 해당 브랜치(PR)에서 작업한 내용 작성
- 로그인 박스 구현을 위해 토큰 값 수정
- FE에서 디코딩이 어려워 로그인 후 토큰 값 반환 시 토큰값을 디코딩해서 유저명, 이메일 주소를 전달하여
로그인 박스에 노출 시킨다. 
다른 영역에서도 필요 시 FE에서 해당 값을 갖고 있다가 노출 시킨다.
<img width="350" alt="스크린샷 2023-08-25 오후 8 49 37" src="https://github.com/wecode-bootcamp-korea/48-2nd-FIVEGUYS-backend/assets/87652668/5db9632b-4e50-4c4d-821a-4174213705a3">

<br />

## :: 테스트 결과 이미지
1. Server가 잘 동작하는지 확인할 수 있는 Terminal 캡쳐 이미지
2. Postman(Client Tool)을 이용한 API 테스트 결과 이미지
<img width="264" alt="스크린샷 2023-08-25 오후 8 53 13" src="https://github.com/wecode-bootcamp-korea/48-2nd-FIVEGUYS-backend/assets/87652668/dfebd727-40c1-4353-816c-2552ea4fd00b">
3. 작성한 Test Code가 잘 통과했는지 확인할 수 있는 이미지
4. DB 작업 PR인 경우 Table 생성 및 수정 결과에 대해 확인할 수 있는 이미지

<br />

## :: 기타 질문 및 특이 사항
- 없습니다.

2023-08-28 08:03 UTC, kyeongraekim requested changes
해당 내용은 token 관련 간단한 수정만 담겨있었다면 바로 머지를 해드렸을텐데, 커밋 기록상 레주메 내용이 함께 동봉되어 있어서 재푸시를 요청드립니다~

2023-08-28 10:15 UTC, kmjmarine commented
token 관련 소스만 다시 커밋 푸쉬 했습니다.
확인 부탁 드립니다.

2023-08-29 06:18 UTC, kmjmarine commented
confilct resolved 했습니다.
확인 부탁 드립니다.

2023-08-29 07:06 UTC, kyeongraekim approved these changes

2023-08-29 07:06 UTC, merged