[ADD] JUMPIT 직무탐색 페이지, 직무탐색 상세 페이지 API 개발
wecode-bootcamp-korea/48-2nd-FIVEGUYS-backend pull request #8
Opened 2023-08-28 07:48 UTC by SIKR2

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [O] 기능 추가
- [ ] 데이터베이스 작업
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 - 해당 브랜치(PR)에서 구현하고자 하는 하나의 목표 작성
- JUMPIT 직무탐색 페이지 및 직무탐색 상세 페이지 구현 목표

<br />

## :: 구현 사항 설명 - 해당 브랜치(PR)에서 작업한 내용 작성
- "직무탐색 페이지 endpoint" -> /positions
- "직무탐색 상세 페이지 endpoint" -> /positions/:jobpostingId
위처럼 routes 경로 설정을 하고, controller, service, dao 등 API 를 만들었습니다.

<br />

## :: 테스트 결과 이미지
1. Server가 잘 동작하는지 확인할 수 있는 Terminal 캡쳐 이미지
<img width="447" alt="스크린샷 2023-08-28 오후 4 46 15" src="https://github.com/wecode-bootcamp-korea/48-2nd-FIVEGUYS-backend/assets/121228839/dc88de6a-b94a-49d2-bd92-fe3e7c89984a">
3. Postman(Client Tool)을 이용한 API 테스트 결과 이미지
<img width="947" alt="스크린샷 2023-08-28 오후 4 46 42" src="https://github.com/wecode-bootcamp-korea/48-2nd-FIVEGUYS-backend/assets/121228839/11bd08a9-6ca4-4862-a120-27fc893fd6ab">
<img width="647" alt="스크린샷 2023-08-28 오후 4 47 06" src="https://github.com/wecode-bootcamp-korea/48-2nd-FIVEGUYS-backend/assets/121228839/74a783a8-1f20-4e8d-88e9-a4017c02a226">
<img width="632" alt="스크린샷 2023-08-28 오후 4 47 24" src="https://github.com/wecode-bootcamp-korea/48-2nd-FIVEGUYS-backend/assets/121228839/489e8fcd-d5a5-4c5b-b1f2-590ca193fe78">

<br />

2023-08-28 08:09 UTC, kyeongraekim requested changes

2023-08-28 08:09 UTC, kyeongraekim commented on api/models/positionsDao.js
> +    console.log(err);
- 내부 개발 로깅을 확인하기 위한 불필요한 콜솔로깅은 상용화될 main으로의 푸시 전에 삭제해주시는 것을 습관화해주세요!

2023-08-28 08:09 UTC, kyeongraekim commented on api/models/positionsDao.js
> +    console.log(err);
- 이곳도 마찬가지입니다!~

2023-08-28 08:09 UTC, kyeongraekim commented on api/controllers/positionsController.js
> +  const jobtypes = await positionsService.getAllJobTypes();
- 가독성을 위해 이곳에 camelCase를 이용한 변수명 관리를 진행해주세요!

2023-08-28 08:20 UTC, SIKR2 commented on api/models/positionsDao.js
> +    console.log(err);
수정하였습니다.

2023-08-28 08:20 UTC, SIKR2 commented on api/models/positionsDao.js
> +    console.log(err);
수정하였습니다.

2023-08-28 08:20 UTC, SIKR2 commented on api/controllers/positionsController.js
> +  const jobtypes = await positionsService.getAllJobTypes();
수정하였습니다.

2023-08-29 03:15 UTC, kyeongraekim approved these changes
LGTM!~

2023-08-29 03:15 UTC, kyeongraekim commented
컨플릭트 해결해주세요!~

2023-08-29 07:42 UTC, SIKR2 commented
conflicts 난 부분 해결하였고, 다시 push 드립니다. 감사합니다!

2023-08-29 07:53 UTC, merged